<a href="https://colab.research.google.com/github/elangbijak4/Riset-Bioinformatika/blob/main/RNA_Sequence_Alignment_Needleman_Wunsch_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## RNA Sequence Alignment: Needleman-Wunsch Algorithm

In [1]:
# Step 1: Data Preparation
seq1 = "AGCU"
seq2 = "ACGU"

In [2]:
# Scoring scheme
match_score = 1
mismatch_score = -1
gap_penalty = -2

In [3]:
# Step 2: Initialize matrices
import numpy as np

n = len(seq1) + 1
m = len(seq2) + 1

In [4]:
# Create scoring and traceback matrices
score_matrix = np.zeros((n, m), dtype=int)
trace_matrix = np.zeros((n, m), dtype=str)

In [5]:
# Initialize the first row and column with gap penalties
for i in range(n):
    score_matrix[i][0] = i * gap_penalty
for j in range(m):
    score_matrix[0][j] = j * gap_penalty

In [6]:
# Fill matrices
for i in range(1, n):
    for j in range(1, m):
        match = score_matrix[i-1][j-1] + (match_score if seq1[i-1] == seq2[j-1] else mismatch_score)
        delete = score_matrix[i-1][j] + gap_penalty
        insert = score_matrix[i][j-1] + gap_penalty
        score_matrix[i][j] = max(match, delete, insert)
        if score_matrix[i][j] == match:
            trace_matrix[i][j] = "↖"
        elif score_matrix[i][j] == delete:
            trace_matrix[i][j] = "↑"
        else:
            trace_matrix[i][j] = "←"

In [7]:
# Step 3: Traceback to get the alignment
align1, align2 = "", ""
i, j = n-1, m-1

while i > 0 or j > 0:
    if trace_matrix[i][j] == "↖":
        align1 = seq1[i-1] + align1
        align2 = seq2[j-1] + align2
        i -= 1
        j -= 1
    elif trace_matrix[i][j] == "↑":
        align1 = seq1[i-1] + align1
        align2 = "-" + align2
        i -= 1
    else:
        align1 = "-" + align1
        align2 = seq2[j-1] + align2
        j -= 1

In [8]:
# Output results
print("Alignment:")
print(align1)
print(align2)
print("\nScore Matrix:")
print(score_matrix)

Alignment:
AGCU
ACGU

Score Matrix:
[[ 0 -2 -4 -6 -8]
 [-2  1 -1 -3 -5]
 [-4 -1  0  0 -2]
 [-6 -3  0 -1 -1]
 [-8 -5 -2 -1  0]]
